"""migration 002

Revision ID: 362346673a1d
Revises: 93c7be39b921
Create Date: 2024-05-15 01:53:14.437778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362346673a1d'
down_revision = '93c7be39b921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'application', ['application_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('application_id')

    # ### end Alembic commands ###
