"""user details added

Revision ID: 3bd309c117d7
Revises: 683fe3bb0183
Create Date: 2024-06-30 14:34:47.001965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd309c117d7'
down_revision = '683fe3bb0183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('street_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lon', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('dob')
        batch_op.drop_column('lat')
        batch_op.drop_column('lon')
        batch_op.drop_column('street_name')
        batch_op.drop_column('city')
        batch_op.drop_column('country')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
