"""migration 0030

Revision ID: 418631830a6d
Revises: eb4e488f8f6a
Create Date: 2024-08-04 17:01:43.111083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418631830a6d'
down_revision = 'eb4e488f8f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('is_official')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_official', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
