"""file format added

Revision ID: 66389bcd8d2c
Revises: b106b7dc3980
Create Date: 2024-07-03 19:53:25.267823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66389bcd8d2c'
down_revision = 'b106b7dc3980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('format')

    # ### end Alembic commands ###
