"""migration 102

Revision ID: 683fe3bb0183
Revises: af04e9d9aad6
Create Date: 2024-05-25 01:19:28.766611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683fe3bb0183'
down_revision = 'af04e9d9aad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('programme_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'programme', ['programme_id'], ['id'])

    with op.batch_alter_table('programme', schema=None) as batch_op:
        batch_op.drop_constraint('programme_application_id_fkey', type_='foreignkey')
        batch_op.drop_column('application_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('programme_application_id_fkey', 'application', ['application_id'], ['id'])

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('programme_id')

    # ### end Alembic commands ###
