"""migration 007

Revision ID: 7840aed93e30
Revises: cc1ede7cf262
Create Date: 2024-05-22 21:39:10.230562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7840aed93e30'
down_revision = 'cc1ede7cf262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('student_application_id_fkey', type_='foreignkey')
        batch_op.drop_column('application_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('student_application_id_fkey', 'application', ['application_id'], ['id'])

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
