"""migration 100

Revision ID: 7b2f6e165565
Revises: 7840aed93e30
Create Date: 2024-05-24 18:04:47.967990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2f6e165565'
down_revision = '7840aed93e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_applicantion', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('expected_applicantion')

    # ### end Alembic commands ###
