"""migration 005

Revision ID: 8f310b7e0e44
Revises: 9e7fb23d6d3a
Create Date: 2024-05-17 00:15:27.187074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f310b7e0e44'
down_revision = '9e7fb23d6d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
