"""user details added

Revision ID: b106b7dc3980
Revises: 3bd309c117d7
Create Date: 2024-06-30 23:47:10.429132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b106b7dc3980'
down_revision = '3bd309c117d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('town', sa.String(length=50), nullable=True))
        batch_op.drop_column('street_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('town')

    # ### end Alembic commands ###
